"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.bgLightMagenta = exports.bgLightBlue = exports.bgLightYellow = exports.bgLightGreen = exports.bgLightRed = exports.bgGray = exports.bgWhite = exports.bgCyan = exports.bgMagenta = exports.bgBlue = exports.bgYellow = exports.bgGreen = exports.bgRed = exports.bgBlack = exports.whiteBright = exports.cyanBright = exports.magentaBright = exports.blueBright = exports.yellowBright = exports.greenBright = exports.redBright = exports.blackBright = exports.lightWhite = exports.lightCyan = exports.lightMagenta = exports.lightBlue = exports.lightYellow = exports.lightGreen = exports.lightRed = exports.gray = exports.white = exports.cyan = exports.magenta = exports.blue = exports.yellow = exports.green = exports.red = exports.black = void 0;
class Text {
    constructor(text) {
        this.styles = [];
        this.text = text;
    }
    addStyle(style) {
        this.styles.push(style);
        return this;
    }
    toString() {
        return `\x1b[${this.styles.join(';')}m${this.text}\x1b[0m`.toString();
    }
}
const black = (text) => new Text(text).addStyle('30').toString();
exports.black = black;
const red = (text) => new Text(text).addStyle('31').toString();
exports.red = red;
const green = (text) => new Text(text).addStyle('32').toString();
exports.green = green;
const yellow = (text) => new Text(text).addStyle('33').toString();
exports.yellow = yellow;
const blue = (text) => new Text(text).addStyle('34').toString();
exports.blue = blue;
const magenta = (text) => new Text(text).addStyle('35').toString();
exports.magenta = magenta;
const cyan = (text) => new Text(text).addStyle('36').toString();
exports.cyan = cyan;
const white = (text) => new Text(text).addStyle('37').toString();
exports.white = white;
const gray = (text) => new Text(text).addStyle('90').toString();
exports.gray = gray;
const lightRed = (text) => new Text(text).addStyle('91').toString();
exports.lightRed = lightRed;
const lightGreen = (text) => new Text(text).addStyle('92').toString();
exports.lightGreen = lightGreen;
const lightYellow = (text) => new Text(text).addStyle('93').toString();
exports.lightYellow = lightYellow;
const lightBlue = (text) => new Text(text).addStyle('94').toString();
exports.lightBlue = lightBlue;
const lightMagenta = (text) => new Text(text).addStyle('95').toString();
exports.lightMagenta = lightMagenta;
const lightCyan = (text) => new Text(text).addStyle('96').toString();
exports.lightCyan = lightCyan;
const lightWhite = (text) => new Text(text).addStyle('97').toString();
exports.lightWhite = lightWhite;
const blackBright = (text) => new Text(text).addStyle('90').addStyle('1').toString();
exports.blackBright = blackBright;
const redBright = (text) => new Text(text).addStyle('91').addStyle('1').toString();
exports.redBright = redBright;
const greenBright = (text) => new Text(text).addStyle('92').addStyle('1').toString();
exports.greenBright = greenBright;
const yellowBright = (text) => new Text(text).addStyle('93').addStyle('1').toString();
exports.yellowBright = yellowBright;
const blueBright = (text) => new Text(text).addStyle('94').addStyle('1').toString();
exports.blueBright = blueBright;
const magentaBright = (text) => new Text(text).addStyle('95').addStyle('1').toString();
exports.magentaBright = magentaBright;
const cyanBright = (text) => new Text(text).addStyle('96').addStyle('1').toString();
exports.cyanBright = cyanBright;
const whiteBright = (text) => new Text(text).addStyle('97').addStyle('1').toString();
exports.whiteBright = whiteBright;
const bgBlack = (text) => new Text(text).addStyle('40').toString();
exports.bgBlack = bgBlack;
const bgRed = (text) => new Text(text).addStyle('41').toString();
exports.bgRed = bgRed;
const bgGreen = (text) => new Text(text).addStyle('42').toString();
exports.bgGreen = bgGreen;
const bgYellow = (text) => new Text(text).addStyle('43').toString();
exports.bgYellow = bgYellow;
const bgBlue = (text) => new Text(text).addStyle('44').toString();
exports.bgBlue = bgBlue;
const bgMagenta = (text) => new Text(text).addStyle('45').toString();
exports.bgMagenta = bgMagenta;
const bgCyan = (text) => new Text(text).addStyle('46').toString();
exports.bgCyan = bgCyan;
const bgWhite = (text) => new Text(text).addStyle('47').toString();
exports.bgWhite = bgWhite;
const bgGray = (text) => new Text(text).addStyle('100').toString();
exports.bgGray = bgGray;
const bgLightRed = (text) => new Text(text).addStyle('101').toString();
exports.bgLightRed = bgLightRed;
const bgLightGreen = (text) => new Text(text).addStyle('102').toString();
exports.bgLightGreen = bgLightGreen;
const bgLightYellow = (text) => new Text(text).addStyle('103').toString();
exports.bgLightYellow = bgLightYellow;
const bgLightBlue = (text) => new Text(text).addStyle('104').toString();
exports.bgLightBlue = bgLightBlue;
const bgLightMagenta = (text) => new Text(text).addStyle('105').toString();
exports.bgLightMagenta = bgLightMagenta;
